## Лабораторная работа по Pandas №5

---
Выполнил: студент группы М8О-103М-20 Воробьев А.В.

---
#### 0. Подключаем необходимые библиотеки:

In [3]:
import numpy as np
import pandas as pd

---
#### 1. Получить от объекта Series показатели описательной статистики:

In [4]:
state = np.random.RandomState(42)
 
s = pd.Series(state.normal(10, 5, 25))
pkz = s.describe()
print(pkz)

count    25.000000
mean      9.182460
std       4.782765
min       0.433599
25%       7.188562
50%       8.829315
75%      12.483571
max      17.896064
dtype: float64


---
#### 2. Узнать частоту уникальных элементов объекта Series (гистограмма):

In [5]:
# создаем объект Series функцией с 
 
data = 'abcdefghik'
len_series = 30
s = pd.Series(np.take(list(data), np.random.randint(len(data), size=len_series)))
 
# считаем число вхождений
ans = s.value_counts()
 
print(ans)

b    7
d    6
k    5
c    3
e    2
i    2
a    2
h    1
g    1
f    1
dtype: int64


---
#### 3. Заменить все элементы объекта Series на "Other", кроме двух наиболее часто встречающихся:

In [6]:
state = np.random.RandomState(42)
s = pd.Series(state.randint(low=1, high=5, size=[13]))
print(s.value_counts())
s[~s.isin(s.value_counts().index[:2])] = 'Other'
print(s)

3    7
1    3
4    2
2    1
dtype: int64
0         3
1     Other
2         1
3         3
4         3
5     Other
6         1
7         1
8         3
9     Other
10        3
11        3
12        3
dtype: object


---
#### 4. Создать объект Series в индексах дата каждый день 2019 года, в значениях случайное значение:

In [8]:
dti = pd.date_range(start='2018-01-01', end='2018-12-31', freq='B') 
s = pd.Series(np.random.rand(len(dti)), index=dti)

---
    4.1. Найти сумму всех вторников:

In [9]:
ans1 = s[s.index.weekday == 2].sum()
print('Сумма всех "вторников"', ans1)
print()

Сумма всех "вторников" 26.809457300944857



---
    4.2. Для каждого месяца найти среднее значение:

In [11]:
ans2 = s.resample('M').mean()
print('Средние значения по месяцам:\n', ans2)
print()

Средние значения по месяцам:
 2018-01-31    0.412844
2018-02-28    0.426648
2018-03-31    0.544774
2018-04-30    0.544896
2018-05-31    0.474830
2018-06-30    0.541264
2018-07-31    0.565644
2018-08-31    0.522916
2018-09-30    0.518667
2018-10-31    0.500500
2018-11-30    0.623204
2018-12-31    0.413053
Freq: M, dtype: float64



---
#### 5. Преобразовать объект Series в DataFrame заданной формы (shape):

In [12]:
s = pd.Series(np.random.randint(low=1, high=10, size=[35]))
 
# преобразование в reshape
r = (7, 5)
 
if r[0] * r[1] != len(s):
    sys.exit('не возможно применить reshape')
    
df = pd.DataFrame(s.values.reshape(r))
 
print(df)

   0  1  2  3  4
0  7  1  3  6  6
1  6  1  5  9  6
2  6  2  8  9  7
3  8  5  6  1  1
4  2  7  5  2  6
5  5  4  1  4  6
6  5  7  2  7  6


---
#### 6. Найти индексы объекта Series кратные 3:

In [17]:
s = pd.Series(np.random.randint(low=1, high=10, size=[7]))
 
# вариант 1
ans1 = np.argwhere(s % 3==0).flatten()
print(ans1)

# вариант 2
ans2 = s[s % 3 == 0].index
print(ans2)

ValueError: Length of passed values is 1, index implies 7.

---
#### 7. Получить данные по индексам объекта Series:

In [16]:
s = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
p = [0, 4, 8, 14, 20, 10]
 
# вариант 1
ans1 = s[p]
print(ans1)
 
# вариант 2 (take - также может использовать многоуровневые массивы)
ans2 = s.take(p)
print(ans2)

0     a
4     e
8     i
14    o
20    u
10    k
dtype: object
0     a
4     e
8     i
14    o
20    u
10    k
dtype: object


---
#### 8. Объединить два объекта Series вертикально и горизонтально:

In [18]:
s1 = pd.Series(range(5))
s2 = pd.Series(list('abcde'))
 
ans_vertical = s1.append(s2)
ans_horizontal = pd.concat([s1, s2], axis=1)
 
print(ans_vertical)
print(ans_horizontal)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


---
#### 9. Получить индексы объекта Series A, данные которых содержатся в объетке Series B:

In [19]:
s1 = pd.Series([5, 3, 2, 1, 4, 11, 13, 8, 7])
s2 = pd.Series([1, 5, 13, 2])
 
# вариант 1 (медленный)
ans1 = np.asarray([np.where(i == s1)[0].tolist()[0] for i in s2])
print(ans1)
 
# вариант 2 (медленный)
ans2 = np.asarray([pd.Index(s1).get_loc(i) for i in s2])
print(ans2)
 
# вариант 3 (быстрый)
ans3 = np.argwhere(s1.isin(s2)).flatten()
print(ans3)

[3 0 6 2]
[3 0 6 2]


ValueError: Length of passed values is 1, index implies 9.

---
#### 10. Получить объект Series B, котоырй содержит элементы без повторений объекта A:

In [20]:
s = pd.Series(np.random.randint(low=1, high=10, size=[10]))
ans = pd.Series(s.unique())
print(ans)

0    2
1    1
2    3
3    7
4    6
5    8
6    4
dtype: int32


---
#### 11. Преобразовать каждый символ объекта Series в верхний регистр:

---
    11.1. Создание объекта Series:

In [22]:
s = pd.Series(['life', 'is', 'interesting'])

---
    11.2. Преобразование данных Series в строку:

In [23]:
s = pd.Series(str(i) for i in s)
 
# вариант 1
ans1 = s.map(lambda x: x.title())
print(ans1)
 
# вариант 1
ans2 = pd.Series(i.title() for i in s)
print(ans2)

0           Life
1             Is
2    Interesting
dtype: object
0           Life
1             Is
2    Interesting
dtype: object


---
#### 12. Рассчитать количество символов в объекте Series:

In [28]:
s = pd.Series(['one', 'two', 'three', 'four', 'five'])

# преобразование в строковый тип
s = pd.Series(str(i) for i in s)

# вариант 1
ans1 = np.asarray(s.map(lambda x: len(x)))
print(ans1)
 
# вариант 2
ans2 = np.asarray([len(i) for i in s])
print(ans2)

<class 'pandas.core.series.Series'>
[3 3 5 4 4]
[3 3 5 4 4]


---
#### 13. Найти разность между объектом Series и смещением объекта Series на n:

In [30]:
n = 1
 
s = pd.Series([1, 5, 7, 8, 12, 15, 17])
 
ans = s.diff(periods=n)
 
print(ans)

0    NaN
1    4.0
2    2.0
3    1.0
4    4.0
5    3.0
6    2.0
dtype: float64


---
#### 14. Преобразовать разные форматы строк объекта Series в дату:

In [31]:
s = pd.Series(['2017/01/01', '2015-02-02', '15 Jan 2019'])
 
# возможно нестабильное решение, необходимо корректно указать строковые значения,
# т.к. могут быть перепутаны месяц и день
ans = pd.to_datetime(s)
 
print(ans)

0   2017-01-01
1   2015-02-02
2   2019-01-15
dtype: datetime64[ns]


---
#### 15. Поскольку работа с датой часто встречается в работе, то см. еще один пример:

---
    15.1. Все данные должны иметь одинаковый формат (часто бывает выгрузка из SQL):

In [32]:
s = pd.Series(['14.02.2019', '22.01.2019', '01.03.2019'])

---
    15.2. Преобразовать в дату:

In [33]:
ans = pd.to_datetime(s, format='%d.%m.%Y')
 
print(ans)

0   2019-02-14
1   2019-01-22
2   2019-03-01
dtype: datetime64[ns]


---
#### 16. Получить год, месяц, день, день недели, номер дня в году от объекта Series (string):

---
    16.1. Распарсить в дату и время:

In [41]:
from dateutil.parser import parse

s = pd.Series(['01 Jan 2018', '02-02-2011', '20120303', '2013/04/04', '2018-12-31'])

s_ts = s.map(lambda x: parse(x, yearfirst=True))

---
    16.2. Получить года:

In [40]:
print(s_ts.dt.year)

0    2018
1    2011
2    2012
3    2013
4    2018
dtype: int64


---
    16.3. Получить месяца:

In [42]:
print(s_ts.dt.month)

0     1
1     2
2     3
3     4
4    12
dtype: int64


---
    16.4. Получить дни:

In [43]:
print(s_ts.dt.day)

0     1
1     2
2     3
3     4
4    31
dtype: int64


---
    16.5. Получить номер недели:

In [44]:
print(s_ts.dt.weekofyear)

0     1
1     5
2     9
3    14
4     1
dtype: int64


<ipython-input-44-22fcabb6c3db>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  print(s_ts.dt.weekofyear)


---
    16.6. Получить номер дня в году:

In [45]:
print(s_ts.dt.dayofyear)

0      1
1     33
2     63
3     94
4    365
dtype: int64


---
#### 17. Отобрать элементы объекта Series, кторые содержат не менее двух гласных:

In [46]:
from collections import Counter
 
s = pd.Series(['Яблоко', 'Orange', 'Plan', 'Python', 'Апельсин', 'Стол', 'Reliance'])
mask = s.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiouаоиеёэыуюя')]) >= 2)
ans = s[mask]
print(ans)

0      Яблоко
1      Orange
4    Апельсин
6    Reliance
dtype: object


---
#### 18. Отобрать e-маилы из объекта Series (можно юзать регулярки):

In [47]:
# модуль для работы с регулярными выражениями
import re
 
emails = pd.Series(['test text @test.com', 'test@mail.ru', 'test.2ru', 'test@pp'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
ans = emails[mask]
print(ans)

1    test@mail.ru
dtype: object


---
#### 19. Получить среднее значение каждого уникального объекта Series s1 через "маску" другого объекта Series s2:

In [51]:
n = 10
s1 = pd.Series(np.random.choice(['dog', 'cat', 'horse', 'bird'], n))
s2 = pd.Series(np.linspace(1,n,n))
ans = s2.groupby(s1).mean()
print(ans)

bird     5.400000
dog      4.333333
horse    7.500000
dtype: float64


---
### Поздравляю!
### Вы прошли еще одну лабу по Pandas!:)

---