---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                
    Кафедра 806 «Вычислительная математика и программирование»  
    Институт: «Информационные технологии и прикладная математика»  
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                


                                            --------------------------------
                                            Лабораторная работа по Pandas №5  
                                            --------------------------------    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Воробьев Алексей Вячеславович  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
---

#### 0. Подключаем необходимые библиотеки:

In [249]:
import numpy as np
import pandas as pd
import sys

---
#### 1. Получить от объекта Series показатели описательной статистики:

In [250]:
state = np.random.RandomState(42)
s = pd.Series(state.normal(10, 5, 25))
#print(s)

pkz = s.describe()
print(pkz)

count    25.000000
mean      9.182460
std       4.782765
min       0.433599
25%       7.188562
50%       8.829315
75%      12.483571
max      17.896064
dtype: float64


---
#### 2. Узнать частоту уникальных элементов объекта Series (гистограмма):

In [251]:
np.set_printoptions(linewidth=750)
data = 'abcdefghik'
print(f'Start object "{data}"\nlen of data = {len(data)}\n---------')
len_series = 30

a = np.random.randint(len(data), size=len_series)
print(f'Start array of indices:\n{a}\nlen of array = {len_series}\n---------')

b = np.take(list(data), a)
print(f'Intersection/union obj and indicates:\n{b}\n----------')

s = pd.Series(b)
ans = s.value_counts()
print(f'Unique values in descending order:\n{ans}')

Start object "abcdefghik"
len of data = 10
---------
Start array of indices:
[1 8 3 3 6 3 0 1 8 3 9 7 1 4 6 8 6 6 3 4 8 3 5 8 6 1 4 4 6 5]
len of array = 30
---------
Intersection/union obj and indicates:
['b' 'i' 'd' 'd' 'g' 'd' 'a' 'b' 'i' 'd' 'k' 'h' 'b' 'e' 'g' 'i' 'g' 'g' 'd' 'e' 'i' 'd' 'f' 'i' 'g' 'b' 'e' 'e' 'g' 'f']
----------
Unique values in descending order:
d    6
g    6
i    5
b    4
e    4
f    2
h    1
a    1
k    1
dtype: int64


---
#### 3. Заменить все элементы объекта Series на "Other", кроме двух наиболее часто встречающихся:

In [252]:
state = np.random.RandomState(42)

a = state.randint(low=1, high=10, size=[15])
print(f'Start random array A:\n{a}\n----------')

s = pd.Series(a)
b = s.value_counts()
print(f'The most common values:\n{b}\n----------')

c = b.index[:2]
#print(f'Two the most common values:\n{c}\n----------')

s[~s.isin(c)] = 'Other'
print(f'Finally with replacement:\n{s}')

Start random array A:
[7 4 8 5 7 3 7 8 5 4 8 8 3 6 5]
----------
The most common values:
8    4
7    3
5    3
4    2
3    2
6    1
dtype: int64
----------
Finally with replacement:
0         7
1     Other
2         8
3     Other
4         7
5     Other
6         7
7         8
8     Other
9     Other
10        8
11        8
12    Other
13    Other
14    Other
dtype: object


---
#### 4. Создать объект Series, в индексах дата каждый день 2019 года, в значениях случайное значение:

In [253]:
dti = pd.date_range(start='2020-01-01', end='2020-12-31', freq='B')
print(f'Start array of Data:\n{dti}\n----------')

a = np.random.randint(0, 100, len(dti))
s = pd.Series(a, index=dti)
print(f'Finally Series:\n{s}')

Start array of Data:
DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
               '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-13', '2020-01-14',
               ...
               '2020-12-18', '2020-12-21', '2020-12-22', '2020-12-23',
               '2020-12-24', '2020-12-25', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31'],
              dtype='datetime64[ns]', length=262, freq='B')
----------
Finally Series:
2020-01-01    58
2020-01-02    54
2020-01-03    22
2020-01-06    91
2020-01-07    22
              ..
2020-12-25    21
2020-12-28    85
2020-12-29    97
2020-12-30    71
2020-12-31    62
Freq: B, Length: 262, dtype: int32


---
    4.1. Найти сумму всех вторников:

In [254]:
b = s[s.index.weekday == 2]
ans1 = b.sum()
print('Сумма всех "вторников" = ', ans1)

Сумма всех "вторников" =  3107


---
    4.2. Для каждого месяца найти среднее значение:

In [255]:
c = s.resample('M')
ans2 = c.mean()
print('Средние значения по месяцам:\n', ans2)

Средние значения по месяцам:
 2020-01-31    53.652174
2020-02-29    54.250000
2020-03-31    46.636364
2020-04-30    53.818182
2020-05-31    52.714286
2020-06-30    47.590909
2020-07-31    51.391304
2020-08-31    49.714286
2020-09-30    62.181818
2020-10-31    55.545455
2020-11-30    54.190476
2020-12-31    57.391304
Freq: M, dtype: float64


---
#### 5. Преобразовать объект Series в DataFrame заданной формы (shape):

In [256]:
s = pd.Series(np.random.randint(low=101, high=201, size=[100]))

r = (10, 10)
if r[0] * r[1] != len(s):
    sys.exit('Не возможно применить reshape')

df = pd.DataFrame(s.values.reshape(r))
print(df)

     0    1    2    3    4    5    6    7    8    9
0  121  139  200  124  183  101  174  116  122  138
1  193  153  142  151  129  163  166  117  150  128
2  195  105  138  169  127  193  193  145  191  124
3  165  196  192  109  104  178  195  195  128  149
4  144  137  170  191  123  195  200  152  113  199
5  127  162  161  112  117  124  125  146  181  118
6  164  174  101  113  158  141  191  159  178  174
7  196  164  123  148  173  184  108  162  127  139
8  103  119  153  156  183  165  171  152  169  109
9  176  199  128  163  155  151  120  132  104  171


---
#### 6. Найти индексы объекта Series кратные 3:

In [257]:
s = pd.Series(np.random.randint(low=1, high=22, size=[10]))

print('Option 1:')
ans1 = np.argwhere((s.index % 3 == 0) & (s.index != 0)).flatten()
print(f'Indices that are multiples of 3:\n{ans1}\n----------')

print('Option 2:')
ans2 = s[(s.index % 3 == 0) & (s.index != 0)]
print(f'Series of elements that are multiples of 3:\n{ans2}')

Option 1:
Indices that are multiples of 3:
[3 6 9]
----------
Option 2:
Series of elements that are multiples of 3:
3    19
6    12
9     2
dtype: int32


---
#### 7. Получить данные по индексам объекта Series:

In [258]:
s = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
p = [0, 4, 8, 14, 20, 10]

ans1 = s[p]
print(f'Option 1:\n{ans1}\n----------')
 
ans2 = s.take(p)
print(f'Option 2:\n{ans2}')

Option 1:
0     a
4     e
8     i
14    o
20    u
10    k
dtype: object
----------
Option 2:
0     a
4     e
8     i
14    o
20    u
10    k
dtype: object


---
#### 8. Объединить два объекта Series вертикально и горизонтально:

In [259]:
s1 = pd.Series(range(5))
s2 = pd.Series(list('abcde'))
 
ans_vertical = s1.append(s2)
ans_horizontal = pd.concat([s1, s2], axis=1)
 
print(ans_vertical)
print(ans_horizontal)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


---
#### 9. Получить индексы объекта Series A, данные которых содержатся в объетке Series B:

In [260]:
s1 = pd.Series([5, 3, 2, 1, 4, 11, 13, 8, 7])
s2 = pd.Series([1, 5, 13, 2])

a = [np.where(i == s1)[0].tolist()[0] for i in s2]
ans1 = np.asarray(a)
print(f'Option 1:\n{ans1}\n----------')

b = [pd.Index(s1).get_loc(i) for i in s2]
ans2 = np.asarray(b)
print(f'Option 2:\n{ans2}\n----------')

c = s1.isin(s2)
ans3 = np.argwhere(c.values).flatten()
print(f'Option 3:\n{c}\n{ans3}')

Option 1:
[3 0 6 2]
----------
Option 2:
[3 0 6 2]
----------
Option 3:
0     True
1    False
2     True
3     True
4    False
5    False
6     True
7    False
8    False
dtype: bool
[0 2 3 6]


---
#### 10. Получить объект Series B, котоырй содержит элементы без повторений объекта A:

In [261]:
s = pd.Series(np.random.randint(low=1, high=10, size=[10]))
ans = pd.Series(s.unique())
print(ans)

0    8
1    3
2    4
3    9
4    6
5    7
6    5
7    2
dtype: int32


---
#### 11. Преобразовать каждый символ объекта Series в верхний регистр:

---
    11.1. Создание объекта Series:

In [262]:
s = pd.Series(['life', 'is', 'interesting'])
s

0           life
1             is
2    interesting
dtype: object

---
    11.2. Преобразование данных Series в строку:

In [263]:
s = pd.Series(str(i) for i in s)

# вариант 1
ans1 = s.map(lambda x: x.title())
print(ans1)

# вариант 1
ans2 = pd.Series(i.title() for i in s)
print(ans2)

0           Life
1             Is
2    Interesting
dtype: object
0           Life
1             Is
2    Interesting
dtype: object


---
#### 12. Рассчитать количество символов в объекте Series:

In [286]:
s = pd.Series(['three'])

# преобразование в строковый тип
s = pd.Series(str(i) for i in s)

print('Option 1')
ans1 = np.asarray(s.map(lambda x: len(set(x))))
print(ans1)
 
print('Option 2')
ans2 = np.asarray([len(i) for i in s])
print(ans2)

print(f'Unique:\n{ans1}')

Option 1
[4]
Option 2
[5]
Unique:
[4]


---
#### 13. Найти разность между объектом Series и смещением объекта Series на n:

In [265]:
n = 1
 
s = pd.Series([1, 5, 7, 8, 12, 15, 17])
 
ans = s.diff(periods=n)
 
print(ans)

0    NaN
1    4.0
2    2.0
3    1.0
4    4.0
5    3.0
6    2.0
dtype: float64


---
#### 14. Преобразовать разные форматы строк объекта Series в дату:

In [266]:
s = pd.Series(['2017/01/01', '2015-02-02', '15 Jan 2019'])
 
# возможно нестабильное решение, необходимо корректно указать строковые значения,
# т.к. могут быть перепутаны месяц и день
ans = pd.to_datetime(s)
 
print(ans)

0   2017-01-01
1   2015-02-02
2   2019-01-15
dtype: datetime64[ns]


---
#### 15. Поскольку работа с датой часто встречается в работе, то см. еще один пример:

---
    15.1. Все данные должны иметь одинаковый формат (часто бывает выгрузка из SQL):

In [267]:
s = pd.Series(['14.02.2019', '22.01.2019', '01.03.2019'])

---
    15.2. Преобразовать в дату:

In [268]:
ans = pd.to_datetime(s, format='%d.%m.%Y')
 
print(ans)

0   2019-02-14
1   2019-01-22
2   2019-03-01
dtype: datetime64[ns]


---
#### 16. Получить год, месяц, день, день недели, номер дня в году от объекта Series (string):

---
    16.1. Распарсить в дату и время:

In [269]:
from dateutil.parser import parse

s = pd.Series(['01 Jan 2018', '02-02-2011', '20120303', '2013/04/04', '2018-12-31'])

s_ts = s.map(lambda x: parse(x, yearfirst=True))

---
    16.2. Получить года:

In [270]:
print(s_ts.dt.year)

0    2018
1    2011
2    2012
3    2013
4    2018
dtype: int64


---
    16.3. Получить месяца:

In [271]:
print(s_ts.dt.month)

0     1
1     2
2     3
3     4
4    12
dtype: int64


---
    16.4. Получить дни:

In [272]:
print(s_ts.dt.day)

0     1
1     2
2     3
3     4
4    31
dtype: int64


---
    16.5. Получить номер недели:

In [273]:
print(s_ts.dt.weekofyear)

0     1
1     5
2     9
3    14
4     1
dtype: int64


<ipython-input-273-22fcabb6c3db>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  print(s_ts.dt.weekofyear)


---
    16.6. Получить номер дня в году:

In [274]:
print(s_ts.dt.dayofyear)

0      1
1     33
2     63
3     94
4    365
dtype: int64


---
#### 17. Отобрать элементы объекта Series, кторые содержат не менее двух гласных:

In [275]:
from collections import Counter
 
s = pd.Series(['Яблоко', 'Orange', 'Plan', 'Python', 'Апельсин', 'Стол', 'Reliance'])
mask = s.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiouаоиеёэыуюя')]) >= 2)
ans = s[mask]
print(ans)

0      Яблоко
1      Orange
4    Апельсин
6    Reliance
dtype: object


---
#### 18. Отобрать e-маилы из объекта Series (можно юзать регулярки):

In [276]:
# модуль для работы с регулярными выражениями
import re
 
emails = pd.Series(['test text @test.com', 'test@mail.ru', 'test.2ru', 'test@pp'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
ans = emails[mask]
print(ans)

1    test@mail.ru
dtype: object


---
#### 19. Получить среднее значение каждого уникального объекта Series s1 через "маску" другого объекта Series s2:

In [277]:
n = 10
s1 = pd.Series(np.random.choice(['dog', 'cat', 'horse', 'bird'], n))
print(s1)

s2 = pd.Series(np.linspace(1, n, n))
print(s2)

ans = s2.groupby(s1).mean()
print(ans)

0    horse
1     bird
2      dog
3    horse
4      cat
5      cat
6      cat
7      dog
8      dog
9      cat
dtype: object
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64
bird     2.000000
cat      7.000000
dog      6.666667
horse    2.500000
dtype: float64


---
### Поздравляю!
### Вы прошли еще одну лабу по Pandas!:)

---