---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                
    Кафедра 806 «Вычислительная математика и программирование»  
    Институт: «Информационные технологии и прикладная математика»  
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                


                                            -------------------------------
                                            Лабораторная работа по NumPy №3  
                                            -------------------------------    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Воробьев Алексей Вячеславович  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
---

#### 0. Подключаем необходимые библиотеки:

In [5]:
import numpy as np

---
#### 1. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением:

In [6]:
a = np.array([1,2,3,4,5])
print(f'Start vector A: {a}\n----------')

n = 1
print(f'Number of zeros N = {n}\n----------')

b = np.zeros(len(a) + (len(a)-1)*n)
print(f'Start vector B:\n{b}\n----------')

b[::n+1] = a
print(f'End vector B:\n{b}')

Start vector A: [1 2 3 4 5]
----------
Number of zeros N = 1
----------
Start vector B:
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
----------
End vector B:
[1. 0. 2. 0. 3. 0. 4. 0. 5.]


---
#### 2. Поменять 2 строки в матрице:

In [7]:
a = np.random.randint(1, 25, (5, 5))
print(f'Start matrix A:\n{a}\n----------')

print('One way:')
a[:2:] = a[1::-1]
print(f'End matix A (1st and 2nd rows are changed):\n{a}\n----------')

print('Another way:')
a[:2:] = a[1::-1]
a[[0, 1]] = a[[1, 0]]
print(f'End matix A (1st and 2nd rows are changed):\n{a}')

Start matrix A:
[[18 12 23  3 10]
 [ 1 15 21 20 16]
 [23 24 23 13 11]
 [ 6  7 22 17  4]
 [16 19 11  9  1]]
----------
One way:
End matix A (1st and 2nd rows are changed):
[[ 1 15 21 20 16]
 [18 12 23  3 10]
 [23 24 23 13 11]
 [ 6  7 22 17  4]
 [16 19 11  9  1]]
----------
Another way:
End matix A (1st and 2nd rows are changed):
[[ 1 15 21 20 16]
 [18 12 23  3 10]
 [23 24 23 13 11]
 [ 6  7 22 17  4]
 [16 19 11  9  1]]


---
#### 3. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники:

In [8]:
np.set_printoptions(linewidth=75, threshold=0)

a = np.random.randint(0, 100, (10, 3))
print(f'Start set of triplets A:\n{a}\n----------')

b = np.repeat(a, 2, axis=1)
print(f'Repeat columns of A (B):\n{b}\n----------')

c = np.roll(b, -1, axis=1)
print(f'Roll columns of B (C):\n{c}\n----------')

d = np.reshape(c, (len(c)*3, 2))
print(f'Reshape of C (D):\n{d}\n----------')

f = np.sort(d, axis=1)
print(f'Sort of D (F):\n{f}\n----------')

g = f.view(dtype=[('p0', f.dtype), ('p1', f.dtype)])
print(f'View of F (G):\n{g}\n----------')

np.set_printoptions(linewidth=50, threshold=1000)
h = np.unique(g)
print(f'Unique of G (H):\n{h}')

Start set of triplets A:
[[87 90 82]
 [76 36 71]
 [79  5 12]
 ...
 [60 94 67]
 [97 63 29]
 [71 64 29]]
----------
Repeat columns of A (B):
[[87 87 90 90 82 82]
 [76 76 36 36 71 71]
 [79 79  5  5 12 12]
 ...
 [60 60 94 94 67 67]
 [97 97 63 63 29 29]
 [71 71 64 64 29 29]]
----------
Roll columns of B (C):
[[87 90 90 82 82 87]
 [76 36 36 71 71 76]
 [79  5  5 12 12 79]
 ...
 [60 94 94 67 67 60]
 [97 63 63 29 29 97]
 [71 64 64 29 29 71]]
----------
Reshape of C (D):
[[87 90]
 [90 82]
 [82 87]
 ...
 [71 64]
 [64 29]
 [29 71]]
----------
Sort of D (F):
[[87 90]
 [82 90]
 [82 87]
 ...
 [64 71]
 [29 64]
 [29 71]]
----------
View of F (G):
[[(87, 90)]
 [(82, 90)]
 [(82, 87)]
 ...
 [(64, 71)]
 [(29, 64)]
 [(29, 71)]]
----------
Unique of G (H):
[( 2, 84) ( 2, 89) ( 5, 12) ( 5, 79) ( 6,  9)
 ( 6, 47) ( 9, 47) (12, 79) (20, 61) (20, 83)
 (29, 63) (29, 64) (29, 71) (29, 97) (36, 71)
 (36, 76) (60, 63) (60, 67) (60, 83) (60, 94)
 (61, 83) (63, 83) (63, 97) (64, 71) (67, 94)
 (71, 76) (82, 87) (82, 90

---
#### 4. Дан массив C; создать массив A, что np.bincount(A) == C:

In [9]:
c = np.bincount([1,1,2,3,4,4,6])
print(f'Start array C:\n{c}\n----------')

b = np.arange(len(c))
print(f'Intermediate array B:\n{b}\n----------')

a = np.repeat(b, c)
print(f'End array A:\n{a}')

Start array C:
[0 2 1 1 2 0 1]
----------
Intermediate array B:
[0 1 2 3 4 5 6]
----------
End array A:
[1 1 2 3 4 4 6]


---
#### 5. Посчитать среднее, используя плавающее окно:

In [44]:
np.set_printoptions(linewidth=100, precision=3, threshold=10)
def moving_average(a, n):
    print('* Start "moving average" function *\n----------')
    ret = np.cumsum(a, dtype=float)
    print(f'Cum Sum of A:\n{ret}\n----------')
    
    print(f'Start ret[{n}:]:\n{ret[n:]}\n----------')
    print(f'ret[:-{n}]:\n{ret[:-n]}\n----------')
    ret[n:] = ret[n:] - ret[:-n]
    
    print(f'End ret[{n}:] = ret[{n}:] - ret[:-{n}]:\n{ret[n:]}\n----------')
    print(f'ret:\n{ret}\n----------')
    return ret[n - 1:] / n

n1 = 10
print(f'Number of elements in B = {n1}\n----------')

n2 = 5
print(f'Number of expelled elements B = {n2}\n----------')

b = np.arange(0, n1)
print(f'Start array B:\n{b}\n----------')

c = moving_average(b, n2)
print(f'Moving average of an B:\n{c}')

Number of elements in B = 10
----------
Number of expelled elements B = 5
----------
Start array B:
[0 1 2 3 4 5 6 7 8 9]
----------
* Start "moving average" function *
----------
Cum Sum of A:
[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]
----------
Start ret[5:]:
[15. 21. 28. 36. 45.]
----------
ret[:-5]:
[ 0.  1.  3.  6. 10.]
----------
End ret[5:] = ret[5:] - ret[:-5]:
[15. 20. 25. 30. 35.]
----------
ret:
[ 0.  1.  3.  6. 10. 15. 20. 25. 30. 35.]
----------
Moving average of an B:
[2. 3. 4. 5. 6. 7.]


In [43]:
def moving_average(a, n):
    
    ret = np.cumsum(a, dtype=float)
    
    ret[n:] = ret[n:] - ret[:-n]
    
    return ret[n - 1:] / n

n1 = 10
print(f'Number of elements in B = {n1}\n----------')

n2 = 3
print(f'Number of expelled elements B = {n2}\n----------')

b = np.arange(0, n1)
print(f'Start array B:\n{b}\n----------')

c = moving_average(b, n2)
print(f'Moving average of an B:\n{c}')

Number of elements in B = 10
----------
Number of expelled elements B = 3
----------
Start array B:
[0 1 2 3 4 5 6 7 8 9]
----------
Moving average of an B:
[1. 2. 3. 4. 5. 6. 7. 8.]


---
#### 6. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1])):

In [11]:
np.set_printoptions(linewidth=100, precision=3, threshold=10000)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    print(f'New shape = {shape}')
    
    strides = (a.itemsize, a.itemsize)
    print(f'Strides of A = {strides}')
    
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

n1 = 10
n2 = 3

b = np.arange(n1)
print(f'Start vector A: {b}\n----------')
print(f'Start shape = {b.shape}')

z = rolling(b, n2)
print(f'----------\nEnd matrix Z:\n{z}')

Start vector A: [0 1 2 3 4 5 6 7 8 9]
----------
Start shape = (10,)
New shape = (8, 3)
Strides of A = (4, 4)
----------
End matrix Z:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


---
#### 7. Инвертировать булево значение, или поменять знак у числового массива без создания нового:

In [12]:
np.set_printoptions(linewidth=80, precision=3, threshold=1000)

a = np.random.randint(0, 2, 20)
print(f'Start array A:\n{a}\n----------')

print(f'Not logical of A:\n{np.logical_not(a, out=a)}')
print('==================================================')

z = np.random.uniform(-1.0, 1.0, 20)
print(f'Start Z:\n{z}\n----------')

print(f'Negative of Z:\n{np.negative(z, out=z)}')

Start array A:
[0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 0]
----------
Not logical of A:
[1 1 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1]
Start Z:
[ 0.682  0.259  0.492  0.677 -0.705  0.915 -0.89   0.224 -0.49  -0.952  0.534
  0.957 -0.256  0.042 -0.329 -0.512  0.914 -0.182 -0.637  0.799]
----------
Negative of Z:
[-0.682 -0.259 -0.492 -0.677  0.705 -0.915  0.89  -0.224  0.49   0.952 -0.534
 -0.957  0.256 -0.042  0.329  0.512 -0.914  0.182  0.637 -0.799]


---
#### 8. Посчитать ранг матрицы:

In [13]:
a = np.random.uniform(0, 1, (10,10))
print(f'Matrix A:\n{a}\n----------')

rank = np.linalg.matrix_rank(a)
print(f'Rank of matrix A = {rank}')

Matrix A:
[[0.306 0.613 0.52  0.222 0.762 0.213 0.568 0.39  0.992 0.411]
 [0.828 0.482 0.69  0.494 0.598 0.057 0.887 0.72  0.658 0.241]
 [0.904 0.449 0.798 0.051 0.601 0.872 0.539 0.36  0.978 0.519]
 [0.508 0.958 0.188 0.07  0.572 0.739 0.067 0.21  0.379 0.97 ]
 [0.53  0.586 0.629 0.682 0.388 0.853 0.459 0.798 0.164 0.65 ]
 [0.572 0.005 0.986 0.875 0.086 0.649 0.156 0.659 0.513 0.675]
 [0.643 0.061 0.971 0.12  0.104 0.792 0.909 0.257 0.479 0.89 ]
 [0.229 0.069 0.609 0.109 0.467 0.441 0.615 0.63  0.941 0.301]
 [0.585 0.125 0.372 0.029 0.726 0.627 0.613 0.075 0.707 0.637]
 [0.968 0.438 0.833 0.977 0.749 0.586 0.524 0.549 0.92  0.186]]
----------
Rank of matrix A = 10


---
#### 9. Найти наиболее частое значение в массиве:

In [33]:
a = np.random.randint(1, 11, 10)
print(f'Start array A:\n{a}\n----------')

b = np.bincount(a)
print(f'Bincount of A:\n{b}\n----------')

c = b.argmax()
print(f'The most common value in A = {c}')

Start array A:
[ 6  7  3  6 10  5  2  2  9  8]
----------
Bincount of A:
[0 0 2 1 0 1 2 1 1 1 1]
----------
The most common value in A = 2


---
#### 10. Извлечь все смежные 3x3 блоки из 10x10 матрицы:

In [15]:
np.set_printoptions(linewidth=80, precision=3, threshold=1000)

a = np.random.randint(1, 10, (4, 4))
print(f'Start matrix A:\n{a}\n----------')

n = 3
print(f'Size of new blocks N = {n}x{n}')
i = 1 + (a.shape[0] - n)
j = 1 + (a.shape[1] - n)
print(f'Number of grid of cortege new A ----- i = {i}')
print(f'Number of cortege of blocks new A --- j = {j}\n----------')

sh = (i, j, n, n)
print(f'New shape = {sh}\n----------')

st = a.strides + a.strides
print(f'Strides = {st}\n----------')

c = stride_tricks.as_strided(a, shape=sh, strides=st)
print(f'Final Extracted Blocks:\n{c}')

Start matrix A:
[[5 1 2 1]
 [9 8 8 3]
 [3 4 7 7]
 [1 7 2 1]]
----------
Size of new blocks N = 3x3
Number of grid of cortege new A ----- i = 2
Number of cortege of blocks new A --- j = 2
----------
New shape = (2, 2, 3, 3)
----------
Strides = (16, 4, 16, 4)
----------
Final Extracted Blocks:
[[[[5 1 2]
   [9 8 8]
   [3 4 7]]

  [[1 2 1]
   [8 8 3]
   [4 7 7]]]


 [[[9 8 8]
   [3 4 7]
   [1 7 2]]

  [[8 8 3]
   [4 7 7]
   [7 2 1]]]]


---
#### 11. Рассмотрим множество матриц (n, n) и множество из P векторов (n,1). Посчитать сумму P произведений матриц (результат имеет размерность (n,1)):

In [16]:
np.set_printoptions(linewidth=80, precision=3, threshold=0)

p, n = 3, 4

m = np.ones((p, n, n))
print(f'Set of matrices ({n}, {n}):\n{m}\n----------')

v = np.ones((p, n, 1))
print(f'Set of {p} Vectors:\n{v}\n----------')

x = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(f'Sum of products of matrices and vectors:\n{x}')

Set of matrices (4, 4):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
----------
Set of 3 Vectors:
[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
----------
Sum of products of matrices and vectors:
[[12.]
 [12.]
 [12.]
 [12.]]


---
12. Дан массив 16x16, посчитать сумму по блокам 4x4:

In [17]:
Z = np.ones((16,16))

k = 4



S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

---
13. Найти n наибольших значений в массиве:

In [18]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9997 9996 9999 9998 9995]


---
14. Построить прямое произведение массивов (все комбинации с каждым элементом):

In [19]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


---
15. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B:

In [20]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 5 6 7]


---
16. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3]):

In [21]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 2 2]
 [2 0 4]
 [2 1 0]
 ...
 [2 0 1]
 [3 3 1]
 [4 3 4]]
[[1 2 2]
 [2 0 4]
 [2 1 0]
 ...
 [2 0 1]
 [3 3 1]
 [4 3 4]]


---
17. Преобразовать вектор чисел в матрицу бинарных представлений:

In [32]:
np.set_printoptions(linewidth=80, precision=3, threshold=1000)

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


---
18. Дан двумерный массив. Найти все различные строки:

In [23]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]]


---
19. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul:

In [29]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/
A = np.ones(10)
B = np.ones(10)

print(np.einsum('i->', A))       # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j', A, B))    # np.outer(A, B)

10.0
[1. 1. 1. ... 1. 1. 1.]
10.0
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


---
## Did you survive?
## No words, you're just the best ...
## Rest, bro, you deserve it!

---