## Лабораторная работа по NumPy №3

Выполнил: студент гр. М8О-103М-20 Воробьев А.В.

---
#### 0. Подключаем необходимые библиотеки:

In [1]:
import numpy as np

---
#### 1. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением:

In [2]:
a = np.array([1,2,3,4,5])
print(f'Start vector A: {a}\n----------')

n = 1
print(f'Number of zeros N = {n}\n----------')

b = np.zeros(len(a) + (len(a)-1)*n)
print(f'Start vector B:\n{b}\n----------')

b[::n+1] = a
print(f'End vector B:\n{b}')

Start vector A: [1 2 3 4 5]
----------
Number of zeros N = 1
----------
Start vector B:
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
----------
End vector B:
[1. 0. 2. 0. 3. 0. 4. 0. 5.]


---
#### 2. Поменять 2 строки в матрице:

In [3]:
a = np.random.randint(1, 25, (5, 5))
print(f'Start matrix A:\n{a}\n----------')

print('One way:')
a[:2:] = a[1::-1]
print(f'End matix A (1st and 2nd rows are changed):\n{a}\n----------')

print('Another way:')
a[:2:] = a[1::-1]
a[[0, 1]] = a[[1, 0]]
print(f'End matix A (1st and 2nd rows are changed):\n{a}')

Start matrix A:
[[17 21 20 16  7]
 [24 10  8 19 19]
 [20 12 10 10  4]
 [24 20  5 18 18]
 [12 21 21 24 20]]
----------
One way:
End matix A (1st and 2nd rows are changed):
[[24 10  8 19 19]
 [17 21 20 16  7]
 [20 12 10 10  4]
 [24 20  5 18 18]
 [12 21 21 24 20]]
----------
Another way:
End matix A (1st and 2nd rows are changed):
[[24 10  8 19 19]
 [17 21 20 16  7]
 [20 12 10 10  4]
 [24 20  5 18 18]
 [12 21 21 24 20]]


---
#### 3. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники:

In [4]:
np.set_printoptions(linewidth=75, threshold=0)

a = np.random.randint(0, 100, (10, 3))
print(f'Start set of triplets A:\n{a}\n----------')

b = np.repeat(a, 2, axis=1)
print(f'Repeat columns of A (B):\n{b}\n----------')

c = np.roll(b, -1, axis=1)
print(f'Roll columns of B (C):\n{c}\n----------')

d = np.reshape(c, (len(c)*3, 2))
print(f'Reshape of C (D):\n{d}\n----------')

f = np.sort(d, axis=1)
print(f'Sort of D (F):\n{f}\n----------')

g = f.view(dtype=[('p0', f.dtype), ('p1', f.dtype)])
print(f'View of F (G):\n{g}\n----------')

np.set_printoptions(linewidth=50, threshold=1000)
h = np.unique(g)
print(f'Unique of G (H):\n{h}')

Start set of triplets A:
[[ 4 79 30]
 [21 71 92]
 [ 9 30 87]
 ...
 [92 71 61]
 [70 20 25]
 [65 45  1]]
----------
Repeat columns of A (B):
[[ 4  4 79 79 30 30]
 [21 21 71 71 92 92]
 [ 9  9 30 30 87 87]
 ...
 [92 92 71 71 61 61]
 [70 70 20 20 25 25]
 [65 65 45 45  1  1]]
----------
Roll columns of B (C):
[[ 4 79 79 30 30  4]
 [21 71 71 92 92 21]
 [ 9 30 30 87 87  9]
 ...
 [92 71 71 61 61 92]
 [70 20 20 25 25 70]
 [65 45 45  1  1 65]]
----------
Reshape of C (D):
[[ 4 79]
 [79 30]
 [30  4]
 ...
 [65 45]
 [45  1]
 [ 1 65]]
----------
Sort of D (F):
[[ 4 79]
 [30 79]
 [ 4 30]
 ...
 [45 65]
 [ 1 45]
 [ 1 65]]
----------
View of F (G):
[[( 4, 79)]
 [(30, 79)]
 [( 4, 30)]
 ...
 [(45, 65)]
 [( 1, 45)]
 [( 1, 65)]]
----------
Unique of G (H):
[( 1, 45) ( 1, 65) ( 4, 30) ( 4, 79) ( 5,  8)
 ( 5, 74) ( 8, 74) ( 9, 30) ( 9, 87) (10, 55)
 (10, 72) (11, 30) (11, 66) (20, 25) (20, 70)
 (21, 71) (21, 92) (25, 70) (28, 64) (28, 68)
 (30, 66) (30, 79) (30, 87) (45, 65) (55, 72)
 (61, 71) (61, 92) (64, 68

---
#### 4. Дан массив C; создать массив A, что np.bincount(A) == C:

In [5]:
c = np.bincount([1,1,2,3,4,4,6])
print(f'Start array C:\n{c}\n----------')

b = np.arange(len(c))
print(f'Intermediate array B:\n{b}\n----------')

a = np.repeat(b, c)
print(f'End array A:\n{a}')

Start array C:
[0 2 1 1 2 0 1]
----------
Intermediate array B:
[0 1 2 3 4 5 6]
----------
End array A:
[1 1 2 3 4 4 6]


---
#### 5. Посчитать среднее, используя плавающее окно:

In [17]:
np.set_printoptions(linewidth=100, precision=3, threshold=10)
def moving_average(a, n):
    #print('* Start "moving average" function *\n----------')
    ret = np.cumsum(a, dtype=float)
    #print(f'Cum Sum of A:\n{ret}\n----------')
    
    #print(f'Start ret[{n}:]:\n{ret[n:]}\n----------')
    
    ret[n:] = ret[n:] - ret[:-n]
    #print(f'ret[:-{n}]:\n{ret[:-n]}\n----------')
    #print(f'End ret[{n}:] = ret[{n}:] - ret[:-{n}]:\n{ret[n:]}\n----------')
    #print(f'ret:\n{ret}\n----------')
    return ret[n - 1:] / n

n1 = 100
print(f'Number of elements in B = {n1}\n----------')

n2 = 23
print(f'Number of expelled elements B = {n2}\n----------')

b = np.arange(1, n1+1)
print(f'Start array B:\n{b}\n----------')

c = moving_average(b, n2)
print(f'Moving average of an B:\n{c}')

Number of elements in B = 100
----------
Number of expelled elements B = 23
----------
Start array B:
[  1   2   3 ...  98  99 100]
----------
Moving average of an B:
[12. 13. 14. ... 87. 88. 89.]


---
#### 6. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1])):

In [41]:
np.set_printoptions(linewidth=100, precision=3, threshold=10000)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    print(f'New shape = {shape}')
    
    strides = (a.itemsize, a.itemsize)
    print(f'Strides of A = {strides}')
    
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

n1 = 10
n2 = 3

b = np.arange(n1)
print(f'Start vector A: {b}\n----------')
print(f'Start shape = {b.shape}')

z = rolling(b, n2)
print(f'----------\nEnd matrix Z:\n{z}')

Start vector A: [0 1 2 3 4 5 6 7 8 9]
----------
Start shape = (10,)
New shape = (8, 3)
Strides of A = (4, 4)
----------
End matrix Z:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


---
#### 7. Инвертировать булево значение, или поменять знак у числового массива без создания нового:

In [93]:
np.set_printoptions(linewidth=80, precision=3, threshold=1000)

a = np.random.randint(0, 2, 20)
print(f'Start array A:\n{a}\n----------')

print(f'Not logical of A:\n{np.logical_not(a, out=a)}')
print('==================================================')

z = np.random.uniform(-1.0, 1.0, 20)
print(f'Start Z:\n{z}\n----------')

print(f'Negative of Z:\n{np.negative(z, out=z)}')

Start array A:
[0 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 0]
----------
Not logical of A:
[1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
Start Z:
[ 0.726  0.302  0.246  0.881  0.452  0.033  0.184 -0.675  0.294  0.985 -0.075
 -0.329 -0.368 -0.931  0.999  0.732 -0.797 -0.094 -0.505  0.359]
----------
Negative of Z:
[-0.726 -0.302 -0.246 -0.881 -0.452 -0.033 -0.184  0.675 -0.294 -0.985  0.075
  0.329  0.368  0.931 -0.999 -0.732  0.797  0.094  0.505 -0.359]


---
#### 8. Посчитать ранг матрицы:

In [91]:
a = np.random.uniform(0, 1, (10,10))
print(f'Matrix A:\n{a}\n----------')

rank = np.linalg.matrix_rank(a)
print(f'Rank of matrix A = {rank}')

Matrix A:
[[0.366 0.413 0.621 0.882 0.999 0.207 0.21  0.766 0.793 0.649]
 [0.159 0.025 0.227 0.472 0.972 0.076 0.459 0.675 0.969 0.205]
 [0.82  0.52  0.869 0.113 0.959 0.724 0.238 0.565 0.582 0.532]
 [0.337 0.603 0.592 0.931 0.877 0.775 0.453 0.686 0.448 0.769]
 [0.238 0.704 0.587 0.101 0.18  0.808 0.386 0.374 0.262 0.164]
 [0.697 0.157 0.725 0.765 0.255 0.871 0.878 0.325 0.581 0.8  ]
 [0.574 0.67  0.39  0.843 0.32  0.916 0.274 0.88  0.93  0.82 ]
 [0.207 0.764 0.509 0.211 0.971 0.423 0.523 0.362 0.137 0.227]
 [0.447 0.969 0.586 0.199 0.493 0.44  0.127 0.788 0.341 0.448]
 [0.589 0.458 0.692 0.294 0.122 0.397 0.63  0.994 0.036 0.1  ]]
----------
Rank of matrix A = 10


---
#### 9. Найти наиболее частое значение в массиве:

In [112]:
a = np.random.randint(1, 11, 100)
print(f'Start array A:\n{a}\n----------')

b = np.bincount(a)
print(f'Bincount of A:\n{b}\n----------')

c = b.argmax()
print(f'The most common value in A = {c}')

Start array A:
[ 4 10  6  5  5  1  9  1  7 10  4 10  8  3  3  8  9 10  3  8  2  8  7  3  2  8
  6 10  5  7  7  8  7  7  2  3 10  8  2  9  8  4  9  5  8  3  2  6 10  2  7  9
  1  3  3 10  3  8 10  8  8  1  4  3 10  8  3  6  4  8  9  7  5  3  5  4 10  2
 10  8  1 10  1  4  6  8  9  2 10  4  9 10 10  1  9  7  7  1  6  5]
----------
Bincount of A:
[ 0  8  8 12  8  7  6 10 16  9 16]
----------
The most common value in A = 8


---
#### 10. Извлечь все смежные 3x3 блоки из 10x10 матрицы:

In [148]:
np.set_printoptions(linewidth=80, precision=3, threshold=1000)

a = np.random.randint(1, 10, (4, 4))
print(f'Start matrix A:\n{a}\n----------')

n = 3
print(f'Size of new blocks N = {n}x{n}')
i = 1 + (a.shape[0] - n)
j = 1 + (a.shape[1] - n)
print(f'Number of grid of cortege new A ----- i = {i}')
print(f'Number of cortege of blocks new A --- j = {j}\n----------')

sh = (i, j, n, n)
print(f'New shape = {sh}\n----------')

st = a.strides + a.strides
print(f'Strides = {st}\n----------')

c = stride_tricks.as_strided(a, shape=sh, strides=st)
print(f'Final Extracted Blocks:\n{c}')

Start matrix A:
[[1 7 5 4]
 [3 1 8 9]
 [5 6 9 3]
 [9 7 7 4]]
----------
Size of new blocks N = 3x3
Number of grid of cortege new A ----- i = 2
Number of cortege of blocks new A --- j = 2
----------
New shape = (2, 2, 3, 3)
----------
Strides = (16, 4, 16, 4)
----------
Final Extracted Blocks:
[[[[1 7 5]
   [3 1 8]
   [5 6 9]]

  [[7 5 4]
   [1 8 9]
   [6 9 3]]]


 [[[3 1 8]
   [5 6 9]
   [9 7 7]]

  [[1 8 9]
   [6 9 3]
   [7 7 4]]]]


---
#### 11. Рассмотрим множество матриц (n, n) и множество из P векторов (n,1). Посчитать сумму P произведений матриц (результат имеет размерность (n,1)):

In [169]:
np.set_printoptions(linewidth=80, precision=3, threshold=0)

p, n = 3, 4

m = np.ones((p, n, n))
print(f'Set of matrices ({n}, {n}):\n{m}\n----------')

v = np.ones((p, n, 1))
print(f'Set of {p} Vectors:\n{v}\n----------')

x = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(f'Sum of products of matrices and vectors:\n{x}')

Set of matrices (4, 4):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
----------
Set of 3 Vectors:
[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
----------
Sum of products of matrices and vectors:
[[12.]
 [12.]
 [12.]
 [12.]]


---
12. Дан массив 16x16, посчитать сумму по блокам 4x4:

In [4]:
Z = np.ones((16,16))

k = 4



S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

---
13. Найти n наибольших значений в массиве:

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

---
14. Построить прямое произведение массивов (все комбинации с каждым элементом):

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

---
15. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B:

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

---
16. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3]):

In [ ]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

---
17. Преобразовать вектор чисел в матрицу бинарных представлений:

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

---
18. Дан двумерный массив. Найти все различные строки:

In [ ]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

---
19. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul:

In [ ]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

---
## Did you survive?
## No words, you're just the best ...
## Rest, bro, you deserve it!

---