---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                
    Кафедра 806 «Вычислительная математика и программирование»  
    Институт: «Информационные технологии и прикладная математика»  
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                


                                            -------------------------------
                                            Лабораторная работа по NumPy №2  
                                            -------------------------------    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Воробьев Алексей Вячеславович  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
---


0. Подключаем библиотеку NumPy:

In [2]:
import numpy as np

-----------------
1. Перемножить матрицы 5x3 и 3x2:

In [10]:
np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan', 
                    precision=8, suppress=False, threshold=1000, formatter=None)

a = np.ones((5, 3))
b = np.ones((3, 2))
c = np.dot(a, b)

print(f'Матрица А:\n{a}\n')
print(f'Матрица Б:\n{b}\n')
print(f'Произведение А на Б:\n{c}\n')

Матрица А:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Матрица Б:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Произведение А на Б:
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]



-----------------
2. Дан массив, поменять знак у элементов, значения которых между 3 и 8:

In [3]:
a = np.arange(20)
a[(a > 3) & (a < 8)] *= -1
print(f'Массив (обратите внимание на значения от 3 до 8):\n{a}')

Массив (обратите внимание на значения от 3 до 8):
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


----------
3. Создать 5x5 матрицу со значениями в строках от 0 до 4:

In [4]:
a = np.zeros((5, 5))
a += np.arange(5)
print(f'Матрица 5х5 со значениями в строках от 0 до 4:\n{a}')

Матрица 5х5 со значениями в строках от 0 до 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


---------------
4. Есть генератор, сделать с его помощью массив:

In [5]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(), float, -1)
print(f'Наш массив от генератора:\n{a}')

Наш массив от генератора:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


-----------------
5. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое:

In [6]:
a = np.around(np.linspace(0, 1, 10), 3)
print(f'Вектооор, о дааа:\n{a}')

Вектооор, о дааа:
[0.    0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889 1.   ]


------------
6. Отсортировать вектор:

In [7]:
a = np.around(np.random.random(12), 3)
a.sort()
print(a)

[0.148 0.173 0.333 0.438 0.49  0.494 0.611 0.644 0.7   0.812 0.866 0.913]


---------
7. Проверить, одинаковы ли 2 numpy массива:

In [8]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 5, 10)
c = np.allclose(a, b)
print(f'Массив 1:\n{a}\n')
print(f'Массив 2:\n{b}\n')
print(f'Сравнение массивов (одинаковы ли):\n{c}')

Массив 1:
[6 3 3 4 5 0 2 4 1 2]

Массив 2:
[4 0 0 3 1 4 0 1 4 0]

Сравнение массивов (одинаковы ли):
False


---
8. Сделать массив неизменяемым

In [9]:
a = np.zeros(10)
print(f'Изначальный массив А:\n{a}\n')

a.flags.writeable = False
print(f'"Заблокированный" массив А:\n{a}\n')

#print('Пытаемся поменять элемент массива...')
#a[0] = 1
#print(f'Кажется, получилось:\n{a}')

Изначальный массив А:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

"Заблокированный" массив А:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]



---
9. Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную:

In [10]:
a = np.random.random([10, 2])
a = np.around(a, 2)
print(f'Исходный массив 10х2 (точки в Декартовой СК):\n{a}\n')

x, y = a[:,0], a[:,1]
print(f'Координаты по оси X:\n{x}')
print(f'Координаты по оси Y:\n{y}\n')

print('Перевод в Полярную СК:\n')

r_vect = np.hypot(x, y)
r_vect = np.around(r_vect, 2)

phi = np.arctan2(y, x)
phi_degr = phi * (180/np.pi)
phi_degr = np.around(phi_degr)

print(f'Значения радиус-вектора:\n{r_vect}')
print(f'Значения угла "фи" в градусах:\n{phi_degr}')

Исходный массив 10х2 (точки в Декартовой СК):
[[0.23 0.32]
 [0.76 0.54]
 [0.94 0.92]
 [0.08 0.28]
 [0.74 0.27]
 [0.47 1.  ]
 [0.01 0.33]
 [0.33 0.32]
 [0.17 0.74]
 [0.4  0.14]]

Координаты по оси X:
[0.23 0.76 0.94 0.08 0.74 0.47 0.01 0.33 0.17 0.4 ]
Координаты по оси Y:
[0.32 0.54 0.92 0.28 0.27 1.   0.33 0.32 0.74 0.14]

Перевод в Полярную СК:

Значения радиус-вектора:
[0.39 0.93 1.32 0.29 0.79 1.1  0.33 0.46 0.76 0.42]
Значения угла "фи" в градусах:
[54. 35. 44. 74. 20. 65. 88. 44. 77. 19.]


---
10. Заменить максимальный элемент на ноль:

In [11]:
a = np.random.random(10)
a = np.around(a, 3)
a = np.sort(a)
print(f'Исходный (отсортированный) массив:\n{a}\n')

a[a.argmax()] = 0
print(f'Массив, где макс. элемент равен нулю:\n{a}')

Исходный (отсортированный) массив:
[0.115 0.148 0.171 0.263 0.266 0.65  0.672 0.716 0.799 0.914]

Массив, где макс. элемент равен нулю:
[0.115 0.148 0.171 0.263 0.266 0.65  0.672 0.716 0.799 0.   ]


---
11. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]:

In [12]:
n = 5
b = np.zeros((n, n), [('x',float),('y',float)])
b['x'], b['y'] = np.meshgrid(np.linspace(0, 1, n), np.linspace(0, 1, n))
print(b)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


---
12. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj)):

In [13]:
n = 10
x = np.arange(1, n + 1)
y = x + 0.5
c = np.around(1.0 / np.subtract.outer(x, y), 2)
print(f'x = {x}\n-----\ny = {y}\n-----\nC is:\n{c}\n-----\n')
print(f'Determinant C = {np.linalg.det(c)}')

x = [ 1  2  3  4  5  6  7  8  9 10]
-----
y = [ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5]
-----
C is:
[[-2.   -0.67 -0.4  -0.29 -0.22 -0.18 -0.15 -0.13 -0.12 -0.11]
 [ 2.   -2.   -0.67 -0.4  -0.29 -0.22 -0.18 -0.15 -0.13 -0.12]
 [ 0.67  2.   -2.   -0.67 -0.4  -0.29 -0.22 -0.18 -0.15 -0.13]
 [ 0.4   0.67  2.   -2.   -0.67 -0.4  -0.29 -0.22 -0.18 -0.15]
 [ 0.29  0.4   0.67  2.   -2.   -0.67 -0.4  -0.29 -0.22 -0.18]
 [ 0.22  0.29  0.4   0.67  2.   -2.   -0.67 -0.4  -0.29 -0.22]
 [ 0.18  0.22  0.29  0.4   0.67  2.   -2.   -0.67 -0.4  -0.29]
 [ 0.15  0.18  0.22  0.29  0.4   0.67  2.   -2.   -0.67 -0.4 ]
 [ 0.13  0.15  0.18  0.22  0.29  0.4   0.67  2.   -2.   -0.67]
 [ 0.12  0.13  0.15  0.18  0.22  0.29  0.4   0.67  2.   -2.  ]]
-----

Determinant C = 34129.86645090223


---
13. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy:

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
    print(f'Minimum of dtype[{dtype}] {np.iinfo(dtype).min}')
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

Minimum of dtype[<class 'numpy.int8'>] -128
127
Minimum of dtype[<class 'numpy.int32'>] -2147483648
2147483647
Minimum of dtype[<class 'numpy.int64'>] -9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


---
14. Напечатать все значения в массиве:

In [15]:
#print(np.get_printoptions()) #отображает настройки
np.set_printoptions(threshold=0)
n = 10
a = np.arange(1, n*n+1).reshape(n, n)
print(f'Shortcut A:\n{a}\n\n--------------------\n')

np.set_printoptions(linewidth=n*n+1, threshold=n*n+1)
print(f'Entire A:\n{a}')

Shortcut A:
[[  1   2   3 ...   8   9  10]
 [ 11  12  13 ...  18  19  20]
 [ 21  22  23 ...  28  29  30]
 ...
 [ 71  72  73 ...  78  79  80]
 [ 81  82  83 ...  88  89  90]
 [ 91  92  93 ...  98  99 100]]

--------------------

Entire A:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


---
15. Найти ближайшее к заданному значению число в заданном массиве:

In [16]:
np.set_printoptions(linewidth=80, precision=2, threshold=1000)

n = 50
a = np.arange(0, n+1, 2)
print(f'Start A:\n{a}\n-----')

b = np.random.uniform(1, n+1)
print(f'Start B = {b}\n-----')

index = (np.abs(a - b)).argmin()
print(f'|A - B|:\n{np.abs(a-b)}\n-----')
print(f'Index = {index}\n-----')

print(f'Nearest value in A = {a[index]}')

Start A:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
-----
Start B = 4.0340610505989405
-----
|A - B|:
[4.03e+00 2.03e+00 3.41e-02 1.97e+00 3.97e+00 5.97e+00 7.97e+00 9.97e+00
 1.20e+01 1.40e+01 1.60e+01 1.80e+01 2.00e+01 2.20e+01 2.40e+01 2.60e+01
 2.80e+01 3.00e+01 3.20e+01 3.40e+01 3.60e+01 3.80e+01 4.00e+01 4.20e+01
 4.40e+01 4.60e+01]
-----
Index = 2
-----
Nearest value in A = 4


---
16. Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b):

In [17]:
np.set_printoptions(linewidth=110, precision=2, threshold=1000)

n = 10
a = np.zeros(n, [ ('position', [ ('x', float),
                                   ('y', float)]),
                    ('color',    [ ('r', float),
                                   ('g', float),
                                   ('b', float)])])
print(f'Start full array A:\n{a}\n----------')

a["color"]["r"] = np.arange(0, 2*n, 2)
a["color"]["g"] = np.arange(1, 2*n+1, 2)
a["color"]["b"] = np.arange(5, 5*n+5, 5)
print(f'Only all colors:\n{a["color"]}\n----------')

a["position"]["x"] = np.arange(15, 15*n+15, 15)
a["position"]["y"] = np.arange(13, 13*n+13, 13)
print(f'Only all positions:\n{a["position"]}\n----------')

print(f'End full array A:\n{a}\n----------')

print('Enter index of A (it will return red color):')
x = a[int(input())]["color"]["r"]
print(f'Your red color = {x}')

Start full array A:
[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
----------
Only all colors:
[( 0.,  1.,  5.) ( 2.,  3., 10.) ( 4.,  5., 15.) ( 6.,  7., 20.) ( 8.,  9., 25.) (10., 11., 30.)
 (12., 13., 35.) (14., 15., 40.) (16., 17., 45.) (18., 19., 50.)]
----------
Only all positions:
[( 15.,  13.) ( 30.,  26.) ( 45.,  39.) ( 60.,  52.) ( 75.,  65.) ( 90.,  78.) (105.,  91.) (120., 104.)
 (135., 117.) (150., 130.)]
----------
End full array A:
[(( 15.,  13.), ( 0.,  1.,  5.)) (( 30.,  26.), ( 2.,  3., 10.)) (( 45.,  39.), ( 4.,  5., 15.))
 (( 60.,  52.), ( 6.,  7., 20.)) (( 75.,  65.), ( 8.,  9., 25.)) (( 90.,  78.), (10., 11., 30.))
 ((105.,  91.), (12., 13., 35.)) ((120., 104.), (14., 15., 40.)) ((135., 117.), (16., 17., 45.))
 ((150., 130.), (18., 19., 50.))]
----------
Enter 

---
17. Дан массив (100,2) координат, найти расстояние от каждой точки до каждой:

In [9]:
np.set_printoptions(linewidth=110, precision=2, threshold=0)

import scipy.spatial

n1 = 3
n2 = 2

a = np.arange(1, n1*n2+1).reshape(n1, n2)
print(f'Start A:\n{a}\n----------')

r = scipy.spatial.distance.cdist(a, a)
print(r)

Start A:
[[1 2]
 [3 4]
 [5 6]]
----------
[[0.   2.83 5.66]
 [2.83 0.   2.83]
 [5.66 2.83 0.  ]]


---
18. Преобразовать массив из float в int:

In [19]:
n = 10
a = np.arange(n, dtype='f4')
print(f'Start array A:\n{a}\n')
print(f'Start type A[i] = {type(a[1])}\n----------\n')

a = a.astype(np.int, copy=False)
print(f'End array A:\n{a}\n')
print(f'End type A[i] = {type(a[1])}\n')

Start array A:
[0. 1. 2. ... 7. 8. 9.]

Start type A[i] = <class 'numpy.float32'>
----------

End array A:
[0 1 2 ... 7 8 9]

End type A[i] = <class 'numpy.int32'>



---
19. Дан файл "LR_NP2_EX19.txt":

    1,2,3,4,5
    6,,,7,8
    ,,9,10,11
    Как прочитать его?

In [5]:
fname = 'LR_NP2_EX19.txt'

a = np.genfromtxt(fname, dtype='U', delimiter=",")

print(f'Our file "LR_NP2_EX19.txt":\n\n{a}')

Our file "LR_NP2_EX19.txt":

[['1' '2' '3' '4' '5']
 ['6' '' '' '7' '8']
 ['' '' '9' '10' '11']]


---
20. Каков эквивалент функции enumerate для numpy массивов?

In [21]:
a = np.arange(1, 28, 3).reshape(3, 3)
print(f'Array A:\n{a}\n----------')

print('First method:')
for index, value in np.ndenumerate(a):
    print(f'String {index[0]+1}:\t{index}, {value}')
print('----------')

print('Second method:')
for index in np.ndindex(a.shape):
    print(f'String {index[0]+1}:\t{index}, {a[index]}')

Array A:
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]
----------
First method:
String 1:	(0, 0), 1
String 1:	(0, 1), 4
String 1:	(0, 2), 7
String 2:	(1, 0), 10
String 2:	(1, 1), 13
String 2:	(1, 2), 16
String 3:	(2, 0), 19
String 3:	(2, 1), 22
String 3:	(2, 2), 25
----------
Second method:
String 1:	(0, 0), 1
String 1:	(0, 1), 4
String 1:	(0, 2), 7
String 2:	(1, 0), 10
String 2:	(1, 1), 13
String 2:	(1, 2), 16
String 3:	(2, 0), 19
String 3:	(2, 1), 22
String 3:	(2, 2), 25


---
21. Сформировать 2D массив с распределением Гаусса:

In [22]:
np.set_printoptions(linewidth=110, precision=2, threshold=0)

x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print(f'X:\n{x}\n----------\nY:\n{y}\n----------')

d = np.hypot(x, y)
print(f'D:\n{d}\n----------')

sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))

np.set_printoptions(linewidth=110, precision=2, threshold=1000)
print(f'G:\n{g}')

X:
[[-1.   -0.78 -0.56 ...  0.56  0.78  1.  ]
 [-1.   -0.78 -0.56 ...  0.56  0.78  1.  ]
 [-1.   -0.78 -0.56 ...  0.56  0.78  1.  ]
 ...
 [-1.   -0.78 -0.56 ...  0.56  0.78  1.  ]
 [-1.   -0.78 -0.56 ...  0.56  0.78  1.  ]
 [-1.   -0.78 -0.56 ...  0.56  0.78  1.  ]]
----------
Y:
[[-1.   -1.   -1.   ... -1.   -1.   -1.  ]
 [-0.78 -0.78 -0.78 ... -0.78 -0.78 -0.78]
 [-0.56 -0.56 -0.56 ... -0.56 -0.56 -0.56]
 ...
 [ 0.56  0.56  0.56 ...  0.56  0.56  0.56]
 [ 0.78  0.78  0.78 ...  0.78  0.78  0.78]
 [ 1.    1.    1.   ...  1.    1.    1.  ]]
----------
D:
[[1.41 1.27 1.14 ... 1.14 1.27 1.41]
 [1.27 1.1  0.96 ... 0.96 1.1  1.27]
 [1.14 0.96 0.79 ... 0.79 0.96 1.14]
 ...
 [1.14 0.96 0.79 ... 0.79 0.96 1.14]
 [1.27 1.1  0.96 ... 0.96 1.1  1.27]
 [1.41 1.27 1.14 ... 1.14 1.27 1.41]]
----------
G:
[[0.37 0.45 0.52 0.57 0.6  0.6  0.57 0.52 0.45 0.37]
 [0.45 0.55 0.63 0.7  0.73 0.73 0.7  0.63 0.55 0.45]
 [0.52 0.63 0.73 0.81 0.85 0.85 0.81 0.73 0.63 0.52]
 [0.57 0.7  0.81 0.89 0.94 0.94 0.89 0.8

---
22. Случайно расположить p элементов в 2D массив:

In [23]:
n = 10
p = 3
b = 100
a = np.zeros((n,n))

ind = np.random.choice(range(n*n), p, replace=False)
print(f'Random indices of P:\n{ind}\n----------')

np.put(a, ind, b)
print(f'2D array A with random P elements:\n{a}')

Random indexes of P:
[71 27 57]
----------
2D array A with random P elements:
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 100.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. 100.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 100.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


---
23. Отнять среднее из каждой строки в матрице:

In [24]:
a = np.arange(0, 25).reshape(5, 5)
print(f'A:\n{a}\n-----')

b = a.mean(axis=1, keepdims=True)
print(f'B (average of A rows/column):\n{b}\n-----')

c = a - b 
print(f'Difference of A and B:\n{c}')

A:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
-----
B (average of A rows/column):
[[ 2.]
 [ 7.]
 [12.]
 [17.]
 [22.]]
-----
Difference of A and B:
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


---
24. Отсортировать матрицу по n-ому столбцу:

In [25]:
a = np.random.randint(0, 10, (5, 5))
n = 0
print(f'A in chaos:\n{a}\n---------')

b = a[:, n].argsort()
print(f'Correct index order:\n{b}\n----------')

c = a[b]
print(f'Put her(A) in order:\n{c}')

A in chaos:
[[0 6 8 6 8]
 [1 9 6 8 6]
 [6 7 0 5 5]
 [5 5 7 1 0]
 [8 8 6 6 5]]
---------
Correct index order:
[0 1 3 2 4]
----------
Put her(A) in order:
[[0 6 8 6 8]
 [1 9 6 8 6]
 [5 5 7 1 0]
 [6 7 0 5 5]
 [8 8 6 6 5]]


---
25. Определить, есть ли в 2D массиве нулевые столбцы:

In [26]:
a = np.zeros((5, 5))
a[:, 0::2] = 1
print(f'A:\n{a}\n-----------')

b = a.any(axis=0)
print(f'What about any non-zero columns in the A?\nAnswer:\t{b}\n---------')

b = ~a.any(axis=0)
print(f'What about any zero columns in the A?\nAnswer:\t{b}\n---------')

c = b.any()
print(f'Is there at least one any zero column in whole A?\nAnswer:\t{c}')

A:
[[1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]]
-----------
What about any non-zero columns in the A?
Answer:	[ True False  True False  True]
---------
What about any zero columns in the A?
Answer:	[False  True False  True False]
---------
Is there at least one any zero column in whole A?
Answer:	True


---
26. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами):

In [73]:
a = np.arange(10, dtype='i2')
print(f'Start A:\n{a}\n----------')
print(f'Bincount A:\n{np.bincount(a, minlength=10)}\n----------')

b = np.random.randint(0, len(a), 20)
print(f'Random B:\n{b}\n----------')
print(f'Bincount B:\n{np.bincount(b, minlength=len(a))}\n----------')

a += np.bincount(b, minlength=len(a))
print(f'Finally A:\n{a}')

Start A:
[0 1 2 3 4 5 6 7 8 9]
----------
Bincount A:
[1 1 1 1 1 1 1 1 1 1]
----------
Random B:
[8 9 3 9 1 1 3 2 8 2 2 9 8 9 4 0 7 9 3 0]
----------
Bincount B:
[2 2 3 3 1 0 0 1 3 5]
----------
Finally A:
[ 2  3  5  6  5  5  6  8 11 14]


---
27. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов:

In [164]:
np.set_printoptions(linewidth=60, threshold=0)

w, h = 4, 4
a = np.random.randint(0, 256, (h, w, 3)).astype(np.ubyte)
print(f'Start A:\n{a}\n----------')

b = 256*256*a[...,0] + 256*a[...,1] + a[...,2]
np.set_printoptions(threshold=1000)
print(f'B:\n{b}\n----------')

print(f'Unique B:\n{np.unique(b)}\n----------')
n = len(np.unique(b))
print(f'Unique N of B = {n}\n----------')

print(f'Unique of A:\n{np.unique(a)}')

Start A:
[[[ 82 172 194]
  [  3 164 199]
  [ 14 249  68]
  [212  67 181]]

 [[ 53 181 109]
  [ 32 216 192]
  [198  50 150]
  [151 121   2]]

 [[211 160  95]
  [169 145 135]
  [196 244  49]
  [237 232 179]]

 [[180  71  11]
  [138  58 122]
  [ 37 106 209]
  [243 221 215]]]
----------
B:
[[ 5418178   238791   981316 13910965]
 [ 3519853  2152640 12989078  9926914]
 [13869151 11112839 12907569 15591603]
 [11814667  9058938  2452177 15982039]]
----------
Unique B:
[  238791   981316  2152640  2452177  3519853  5418178
  9058938  9926914 11112839 11814667 12907569 12989078
 13869151 13910965 15591603 15982039]
----------
Unique N of B = 16
----------
Unique of A:
[  2   3  11  14  32  37  49  50  53  58  67  68  71  82
  95 106 109 121 122 135 138 145 150 151 160 164 169 172
 179 180 181 192 194 196 198 199 209 211 212 215 216 221
 232 237 243 244 249]


---
28. Дан четырехмерный массив, посчитать сумму по последним двум осям:

In [268]:
np.set_printoptions(linewidth=100, threshold=0)
x = 4
y = 5
z = 3
t = 2
print(f'''Number of rows\t-------\tX = {x}\nNumber of columns -----\tY = {y}
Number of blocks ------\tZ = {z}\nNumber of grid --------\tT = {v}\n----------''')

a = np.random.randint(1, 10, (t, z, x, y))
print(f'Start A:\n{a}\n----------')

b = a.shape[:-2] + (-1,)
print(f'Shape B: {b}\n---------')

r =a.reshape(b)
print(f'Reshape A in B:\n{a.reshape(b)}\n----------')

c = r.sum(axis=-1, keepdims=True)
print(f'Sum by rows and columns:\n{c}')

Number of rows	-------	X = 4
Number of columns -----	Y = 5
Number of blocks ------	Z = 3
Number of grid --------	T = 2
----------
Start A:
[[[[5 3 2 2 7]
   [1 2 8 7 7]
   [2 1 7 2 5]
   [9 6 5 7 5]]

  [[1 1 9 6 9]
   [5 9 9 6 2]
   [5 5 8 6 4]
   [7 3 1 1 2]]

  [[3 6 9 7 4]
   [2 1 3 6 1]
   [4 8 5 9 7]
   [1 7 7 1 9]]]


 [[[1 3 4 4 5]
   [9 4 6 5 5]
   [2 2 1 2 4]
   [9 7 5 7 8]]

  [[6 8 3 1 1]
   [4 5 5 9 4]
   [4 6 4 5 4]
   [8 2 3 5 6]]

  [[9 8 5 4 7]
   [3 5 5 6 5]
   [7 5 4 7 8]
   [2 9 1 6 5]]]]
----------
Shape B: (2, 3, -1)
---------
Reshape A in B:
[[[5 3 2 ... 5 7 5]
  [1 1 9 ... 1 1 2]
  [3 6 9 ... 7 1 9]]

 [[1 3 4 ... 5 7 8]
  [6 8 3 ... 3 5 6]
  [9 8 5 ... 1 6 5]]]
----------
Sum by rows and columns:
[[[ 93]
  [ 99]
  [100]]

 [[ 93]
  [ 93]
  [111]]]


---
29. Найти диагональные элементы произведения матриц:

In [296]:
np.set_printoptions(linewidth=100, threshold=0)

x = 30
y = 50

a = np.random.randint(1, 10, (x, y))
print(f'Matrix A:\n{a}\n----------')

b = np.random.randint(1, 20, (y, x))
print(f'Matrix B:\n{b}\n----------')

c = np.dot(a, b)
print(f'Multiplication of matrices A and B: C = A * B\n{c}\n----------')

d = np.diag(c)
print(f'Diagonal elements of C:\n{d}')

Matrix A:
[[6 1 2 ... 5 4 3]
 [6 7 9 ... 5 8 3]
 [2 3 9 ... 1 5 9]
 ...
 [5 1 1 ... 1 2 4]
 [7 3 2 ... 7 8 9]
 [3 4 7 ... 4 7 1]]
----------
Matrix B:
[[12 15 11 ... 14 12  2]
 [17 12  6 ... 11  9 16]
 [13  8  4 ... 11 13 10]
 ...
 [ 6 17 10 ...  4 11  3]
 [15 10 17 ...  7 13 17]
 [ 5 16 17 ... 11 16 19]]
----------
Multiplication of matrices A and B: C = A * B
[[2733 3047 2887 ... 2737 2561 2890]
 [2583 2950 2605 ... 2500 2456 2590]
 [2543 3136 2806 ... 2493 2606 2696]
 ...
 [2693 3088 2887 ... 2712 2707 2749]
 [2554 3056 2923 ... 2475 2599 2749]
 [2767 2999 2691 ... 2790 2423 2803]]
----------
Diagonal elements of C:
[2733 2950 2806 ... 2712 2599 2803]


---
## My congratulations!
## You completed NumPy Lab # 2 !

---